name = "pvsf-archive"
compatibility_date = "2024-01-01"

# Cloudflare Pages設定
pages_build_output_dir = "out"

[build]
command = "npm run build"

[env.production]
route = "pvsf.jp/*"
 
[[env.production.routes]]
pattern = "pvsf.jp/*"
zone_name = "pvsf.jp" 